// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5F_6J_8VDMbf7b4U_wIk_Z0HdYDRaDo',
    appId: '1:847585068690:web:763200ebca6fe684d4884b',
    messagingSenderId: '847585068690',
    projectId: 'abrafleet-cec94',
    authDomain: 'abrafleet-cec94.firebaseapp.com',
    databaseURL: 'https://abrafleet-cec94-default-rtdb.firebaseio.com',
    storageBucket: 'abrafleet-cec94.firebasestorage.app',
    measurementId: 'G-GLPPBHGCGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLT6uzNQ6KQIpbONoYmCY8ATAsyabkUQ',
    appId: '1:847585068690:android:c3e572ad3a9a6cf3d4884b',
    messagingSenderId: '847585068690',
    projectId: 'abrafleet-cec94',
    databaseURL: 'https://abrafleet-cec94-default-rtdb.firebaseio.com',
    storageBucket: 'abrafleet-cec94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv7A1J7bGmA43hFIqqAzEXmay3g1VClE8',
    appId: '1:847585068690:ios:19538e1e64f56981d4884b',
    messagingSenderId: '847585068690',
    projectId: 'abrafleet-cec94',
    databaseURL: 'https://abrafleet-cec94-default-rtdb.firebaseio.com',
    storageBucket: 'abrafleet-cec94.firebasestorage.app',
    androidClientId: '847585068690-mad8v1cgnc17s5eso76k622khqhe4jbl.apps.googleusercontent.com',
    iosClientId: '847585068690-grde09iv76rnuvpqqqr1naaherdjd02r.apps.googleusercontent.com',
    iosBundleId: 'com.example.abraFleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv7A1J7bGmA43hFIqqAzEXmay3g1VClE8',
    appId: '1:847585068690:ios:19538e1e64f56981d4884b',
    messagingSenderId: '847585068690',
    projectId: 'abrafleet-cec94',
    databaseURL: 'https://abrafleet-cec94-default-rtdb.firebaseio.com',
    storageBucket: 'abrafleet-cec94.firebasestorage.app',
    androidClientId: '847585068690-mad8v1cgnc17s5eso76k622khqhe4jbl.apps.googleusercontent.com',
    iosClientId: '847585068690-grde09iv76rnuvpqqqr1naaherdjd02r.apps.googleusercontent.com',
    iosBundleId: 'com.example.abraFleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5F_6J_8VDMbf7b4U_wIk_Z0HdYDRaDo',
    appId: '1:847585068690:web:61e06c0c261185cfd4884b',
    messagingSenderId: '847585068690',
    projectId: 'abrafleet-cec94',
    authDomain: 'abrafleet-cec94.firebaseapp.com',
    databaseURL: 'https://abrafleet-cec94-default-rtdb.firebaseio.com',
    storageBucket: 'abrafleet-cec94.firebasestorage.app',
    measurementId: 'G-G5ZVYZ9W0N',
  );

}